name: 'Backend-CI'

# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:

  # Automatic trigger on push events to the main branch
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11    
    - name: Run Linter
      run: |
        pip install flake8
        flake8 .  
  build:
    needs: lint
    runs-on: ubuntu-latest 
    steps: 
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11          
    - name: Build Application
      run: |
        cd solution/backend
        pip install pipenv
        pipenv install --dev        
  test:
    needs: build
    runs-on: ubuntu-latest 
    steps: 
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11    
    
    - name: Install Pipenv
      run: pip install pipenv
      working-directory: solution/backend
    
    - name: Install dependencies
      run: pipenv install --dev
      working-directory: solution/backend
    
    - name: Run tests
      run: pipenv run test
      working-directory: solution/backend

     
