name: 'Backend-CI'

# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:

  # Automatic trigger on push events to the main branch
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest    
    
    steps:
    - uses: actions/checkout@v3
    - name: Run Linter
      run: |
        pip install flake8
        flake8 .  
  build:
    needs: lint
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v3
    - name: Build Application
      run: |
        pip install -r requirements.txt
        python setup.py build        
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Tests
      run: |
        pip install -r requirements.txt
        pytest        
