name: 'Backend-CI'

# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:

  # Automatic trigger on push events to the main branch
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    # Steps in the job
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: latest
    - name: Install dependencies
      run: cd solution/backend && npm ci      
    - name: Run tests
      run: cd solution/backend && npm test      
  lint:
    runs-on: ubuntu-latest
    # Steps in the job
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: latest
    - name: Install dependencies
      run: cd solution/backend && npm ci      
    - name: Run lint
      run: cd solution/backend && npm run lint
  build:
        needs: [test, lint]
        runs-on: ubuntu-latest
        steps:
          - name: Check out repository
            uses: actions/checkout@v3
          - name: Use Node.js 
            uses: actions/setup-node@v3
            with:
              node-version: latest        