name: 'Frontend-CI'

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: 
      name: staging

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Cache npm dependencies
      uses: actions/cache@v2
      with:
        path: solution/frontend/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('solution/frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-         

    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: latest
    - name: Install dependencies
      run: cd solution/frontend && npm ci      
    - name: Run tests
      run: cd solution/frontend && npm test      
  lint:
    runs-on: ubuntu-latest
    environment: 
      name: staging

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Cache npm dependencies
      uses: actions/cache@v2
      with:
        path: solution/frontend/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('solution/frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-         

    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: latest
    - name: Install dependencies
      run: cd solution/frontend && npm ci      
    - name: Run lint
      run: cd solution/frontend && npm run lint
  build:
    needs: [test, lint]
    runs-on: ubuntu-latest
    environment:
      name: staging        
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: solution/frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('solution/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-           

      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get Git SHA
        run: echo "GIT_SHA=$(echo ${{ github.sha }})"        

      - name: Build Docker image
        run: |
          cd solution/frontend && docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag movies-frontend:${{ github.sha }} .        

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: aws ecr get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS --password-stdin ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com

      - name: Tag Docker image for Amazon ECR
        run: docker tag movies-frontend:${{ github.sha }} ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/movies-frontend:${{ github.sha }}

      - name: Push Docker image to Amazon ECR
        run: docker push ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/movies-frontend:${{ github.sha }}